Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false
  
Metrics/PerceivedComplexity:
  Enabled: false
  
Style/ClassVars:
  Enabled: false
  
